name: Docs
on: 
  push:
    branches:
      - '*'
  
jobs:
  move-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Push docs file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source_file: 'docs/main.json'
          destination_repo: 'lunar-js/docs'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          user_name: 'github-actions[bot]'
          commit_message: 'Push docs file to docs repo'
